apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: todoapp
spec:
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      nodeSelector:
        gpu: nvidia
      containers:
      - name: mysqldb
        image: mysql
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_DATABASE
        volumeMounts:
        - name: dbpath
          mountPath: /var/lib/mysql
      volumes:
      - name: dbpath
        persistentVolumeClaim:
          claimName: mydbpvc
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: todoapp
spec:
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      nodeSelector:
        gpu: nvidia
      containers:
      - name: todoapi
        image: sumeetkumarnaik/todoapimysql:1.0
        ports:
        - containerPort: 80
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_HOST
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
